//-------------------------------------------------------------------------
// Help panel definitions
//
// Id's                 Purpose
// --------             -------
// 1-63                 Help tables
// 64-127               Sub-help tables
// 128-191              Extended help panels
// 192-255              Key help panels
// 256-1023             Menu item help panels
// 1024-3327            Dialog field panels
// 3328   -4095         Error message help
// (0xD00) (0xFFF)
// 4096-                Hyper-linked, footnote, and misc. help panels
//-------------------------------------------------------------------------
#define HELP_SETTINGS            1
#define SUBHELP_SETTINGS         64
#define EXTHELP_SETTINGS         128
#define PNL_GAMEOFLIFE           4096
#define PNL_SETTINGS             4097
#define PNL_BUTTONS              4098
