#define DLG_SETTINGS             256
#define WND_SAVER                257

#define DST_SL_TIMEOUT           512
#define DST_EF_TIMEOUT           513
#define DST_CB_DISABLE           514
#define DST_PB_SET               515
#define DST_PB_APPLY             516
#define DST_PB_UNDO              517
#define DST_PB_HELP              518

#define BMP_SPACE                1024

#define STR_TITLE                1
#define STR_HELPTITLE            2
